import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Zspan Zli",
    artist: "Ospan Ali",
    price:  800,
    discount: 10,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101167/ospan-ali-6xv4A1VA1rU-unsplash_ymbtrp.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Zharlie Zreen",
    artist: "Art Hauntington",
    price:  1200,
    discount: 10,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101815/charlie-green-3JmfENcL24M-unsplash_xvhqfj.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Zndriyko Zodilynk",
    artist: "Andriyko Podilynk",
    price:  400,
    discount: 10,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101359/andriyko-podilnyk-JxfYO0hhZGQ-unsplash_n57aiz.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Zrt Zauntington",
    artist: "Art Hauntington",
    price:  1600,
    discount: 10,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101473/art-hauntington-jzY0KRJopEI-unsplash_gmxp5q.jpg",
    categoryName: "Photography"
  },
  {
    _id: uuid(),
    title: "Zrooklyn Zozak",
    artist: "Alan Scales",
    price:  400,
    discount: 20,
    rating: 4.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101180/brooklyn-MO5qO9xpZhA-unsplash_jbvfhj.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zlan Zcales",
    artist: "Alan Scales",
    price:  800,
    discount: 20,
    rating: 3.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101151/alan-scales-1_WMZARl81c-unsplash_wxogyv.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zirmingham Zuseum",
    artist: "Birmingham Museum",
    price:  1200,
    discount: 20,
    rating: 2.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650102233/birmingham-museums-trust-5F3u0j6s6pM-unsplash_nxfxvt.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zr Zorpa",
    artist: "Jr Korpa",
    price:  800,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650102701/jr-korpa-O-p6tKWPPig-unsplash_jna950.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zndreas Zickl",
    artist: "Andreas Fickl",
    price:  400,
    discount: 20,
    rating: 4.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650103212/andreas-fickl-o1xcUi-Yt_w-unsplash_x3rqpc.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zrooke Zark",
    artist: "Brooke Lark",
    price:  1200,
    discount: 20,
    rating: 3.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650103208/brooke-lark-V4MBq8kue3U-unsplash_ar4mlm.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zavisuko",
    artist: "Orfeas Green",
    price:  1600,
    discount: 20,
    rating: 2.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650103204/davisuko-5E5N49RWtbA-unsplash_usky7y.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zlcarito",
    artist: "Elcarito",
    price:  800,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650103202/elcarito-XxER0_5jblI-unsplash_us9tlp.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zlcarito",
    artist: "Robert Keane",
    price:  2400,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650103966/robert-keane-mPJqwk-kAWw-unsplash_d2uwmj.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zlexander Znt",
    artist: "Orfeas Green",
    price:  3600,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650103914/alexander-ant-r7xdS9hjYYE-unsplash_g8sliu.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Europeana",
    artist: "Zuropeana",
    price:  1200,
    discount: 30,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650101186/europeana-5TK1F5VfdIk-unsplash_ziromp.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Zlara Zulikova",
    artist: "Klara Kulikova",
    price:  800,
    discount: 30,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104263/klara-kulikova-kiLdjFm2y14-unsplash_vwiz0t.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Zrfeas Zreen",
    artist: "Orfeas Green",
    price:  400,
    discount: 30,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104256/orfeas-green-G5A5ZNjS2tE-unsplash_dvkmg9.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Federico Zi Zio",
    artist: "Orfeas Green",
    price:  800,
    discount: 30,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104251/federico-di-dio-photography-XVOBr3F95RY-unsplash_op2l2a.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Basel",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image//upload/c_scale,w_328/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Zuropeana",
    artist: "Europeana",
    price:  400,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104645/europeana-hSkbqHnt-g4-unsplash_y7awbi.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Zirmigham Zuseum",
    artist: "Birmigham Museum Trust",
    price:  2400,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104647/birmingham-museums-trust-5ruS8plfbvM-unsplash_agok2q.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Europeana",
    price:  1600,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104650/birmingham-museums-trust-e0wBK0xJXYQ-unsplash_mta2sj.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Imleedh Zli",
    artist: "Imleedh Ali",
    price:  800,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104992/imleedh-ali-Uf-_p8zZiT8-unsplash_drs2iq.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Zaron Burden",
    artist: "Silas Baisch",
    price:  800,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104990/aaron-burden-dXYE1d08BiY-unsplash_n7bozj.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Znastasia Zaioglou",
    artist: "Anastasia Taioglou",
    price:  6400,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104978/anastasia-taioglou-CTivHyiTbFw-unsplash_nvsatm.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Zilas Zaisch",
    artist: "Silas Baisch",
    price:  1600,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650104989/silas-baisch-K785Da4A_JA-unsplash_pg4px1.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Rachel Zcdermott",
    artist: "Rachel Mcdermott",
    price:  1200,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650105295/rachel-mcdermott-0fN7Fxv1eWA-unsplash_smjrhm.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Danie Franco",
    artist: "Danie Franco",
    price:  5600,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650105294/danie-franco-l9I93gZKTG4-unsplash_myhaha.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Zichard Zaimes",
    artist: "Ronan Kruithof",
    price:  1600,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650105292/richard-jaimes-s97-KYat9sA-unsplash_j4xnwg.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Zonan Zruithof",
    artist: "Ronan Kruithof",
    price:  400,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/c_scale,w_328/v1650105291/ronan-kruithof-fSJs-cTmT94-unsplash_d1yzzz.jpg",
    categoryName: "Portraits",
  },
];
