import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Zspan Zli",
    artist: "Ospan Ali",
    price:  800,
    discount: 10,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650101167/ospan-ali-6xv4A1VA1rU-unsplash_ymbtrp.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Zharlie Zreen",
    artist: "Charlie Green",
    price:  1200,
    discount: 10,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650101815/charlie-green-3JmfENcL24M-unsplash_xvhqfj.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Zndriyko Zodilynk",
    artist: "Andriyko Podilynk",
    price:  400,
    discount: 10,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650101359/andriyko-podilnyk-JxfYO0hhZGQ-unsplash_n57aiz.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Zrt Zauntington",
    artist: "Art Hauntington",
    price:  1600,
    discount: 10,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650101473/art-hauntington-jzY0KRJopEI-unsplash_gmxp5q.jpg",
    categoryName: "Photography"
  },
  {
    _id: uuid(),
    title: "Zrooklyn Zozak",
    artist: "Brooklyn Mozak",
    price:  400,
    discount: 20,
    rating: 4.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650101180/brooklyn-MO5qO9xpZhA-unsplash_jbvfhj.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zlan Zcales",
    artist: "Alan Scales",
    price:  800,
    discount: 20,
    rating: 3.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650101151/alan-scales-1_WMZARl81c-unsplash_wxogyv.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zirmingham Zuseum",
    artist: "Birmingham Museum",
    price:  1200,
    discount: 20,
    rating: 2.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650102233/birmingham-museums-trust-5F3u0j6s6pM-unsplash_nxfxvt.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zr Zorpa",
    artist: "Jr Korpa",
    price:  800,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650102701/jr-korpa-O-p6tKWPPig-unsplash_jna950.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Zndreas Zickl",
    artist: "Andreas Fickl",
    price:  400,
    discount: 20,
    rating: 4.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650103212/andreas-fickl-o1xcUi-Yt_w-unsplash_x3rqpc.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zrooke Zark",
    artist: "Brooke Lark",
    price:  1200,
    discount: 20,
    rating: 3.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650103208/brooke-lark-V4MBq8kue3U-unsplash_ar4mlm.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zavisuko",
    artist: "Davisuko",
    price:  1600,
    discount: 20,
    rating: 2.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650103204/davisuko-5E5N49RWtbA-unsplash_usky7y.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Zlcarito",
    artist: "Elcarito",
    price:  400,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1650103202/elcarito-XxER0_5jblI-unsplash_us9tlp.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green1",
    price:  1200,
    discount: 30,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green2",
    price:  800,
    discount: 30,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green2",
    price:  400,
    discount: 30,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green3",
    price:  400,
    discount: 30,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green4",
    price:  400,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green4",
    price:  400,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green5",
    price:  400,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green1",
    price:  1600,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green2",
    price:  400,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green3",
    price:  800,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green3",
    price:  1200,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green4",
    price:  1600,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green1",
    price:  1200,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green2",
    price:  1200,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green1",
    price:  1600,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green1",
    price:  800,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
];
