import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Abstract New1",
    artist: "Rachel Green1",
    price:  800,
    discount: 10,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Abstract New2",
    artist: "Rachel Green1",
    price:  1200,
    discount: 10,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081717/avatar-2_mkzjaw.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Abstract New3",
    artist: "Rachel Green2",
    price:  400,
    discount: 10,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081299/cld-sample.jpg",
    categoryName: "Photography",
  },
  {
    _id: uuid(),
    title: "Abstract New4",
    artist: "Rachel Green2",
    price:  1600,
    discount: 10,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081276/sample.jpg",
    categoryName: "Photography"
  },
  {
    _id: uuid(),
    title: "You are Winner1",
    artist: "Junaid Qureshi",
    price:  400,
    discount: 20,
    rating: 4.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081718/portrait-5_nrwqhi.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "You are Winner2",
    artist: "Junaid Qureshi",
    price:  400,
    discount: 20,
    rating: 3.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081718/portrait-5_nrwqhi.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "You are Winner3",
    artist: "Junaid Qureshi",
    price:  400,
    discount: 20,
    rating: 2.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081718/portrait-5_nrwqhi.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "You are Winner4",
    artist: "Junaid Qureshi",
    price:  400,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081718/portrait-5_nrwqhi.jpg",
    categoryName: "Impressionism",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich1",
    artist: "Shiv Khera",
    price:  400,
    discount: 20,
    rating: 4.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081719/portrait-7_kymgrl.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich2",
    artist: "Shiv Khera",
    price:  400,
    discount: 20,
    rating: 3.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081719/portrait-7_kymgrl.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich3",
    artist: "Shiv Khera",
    price:  400,
    discount: 20,
    rating: 2.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081719/portrait-7_kymgrl.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich4",
    artist: "Shiv Khera",
    price:  400,
    discount: 20,
    rating: 1.9,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081719/portrait-7_kymgrl.jpg",
    categoryName: "PopArt",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 30,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 30,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 30,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 30,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/collection-2_knhw2x.jpg",
    categoryName: "Oil Paintings",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-1_m3tz5h.jpg",
    categoryName: "Basel Works",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081715/collection-3_b9ops9.jpg",
    categoryName: "Water",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 4.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 3.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 2.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
  {
    _id: uuid(),
    title: "Abstract Instrument",
    artist: "Rachel Green",
    price:  400,
    discount: 40,
    rating: 1.5,
    imageUrl: "https://res.cloudinary.com/duddwta8d/image/upload/v1648081716/portrait-1_h1pmf1.jpg",
    categoryName: "Portraits",
  },
];
